"""Milestone 3 — Kickoff: ensure a Calendly link exists for the AM to share.

The Calendly link itself was generated by the welcome milestone; this step
just promotes it to a milestone-level artifact and marks complete. (If the
welcome milestone hasn't run — e.g. partial recovery — we generate one here.)

There is no external email here: the welcome email already contains the
link. We leave it `done` once the link is recorded, so subsequent flows can
read `run.milestones[KICKOFF].artifacts['url']`.
"""

from __future__ import annotations

from ..integrations import IntegrationBundle
from ..logging_setup import get_logger
from ..schemas import MilestoneName, MilestoneState, OnboardingRun
from ..state import Store
from ..state.idempotency import run_idempotent
from ..state.transitions import transition

log = get_logger(__name__)


def run(run: OnboardingRun, store: Store, clients: IntegrationBundle) -> None:
    transition(store, run, MilestoneName.KICKOFF, MilestoneState.RUNNING)

    primary_email = (
        run.contract.client_contacts[0].email
        if run.contract.client_contacts
        else "client@example.com"
    )

    link = run_idempotent(
        store,
        run.run_id,
        MilestoneName.KICKOFF,
        "calendly_link",
        lambda: _calendly(clients, run, primary_email),
    )

    transition(
        store,
        run,
        MilestoneName.KICKOFF,
        MilestoneState.DONE,
        artifacts={"calendly_url": link["url"]},
    )


def _calendly(clients: IntegrationBundle, run: OnboardingRun, email: str) -> dict:
    link = clients.calendly.scheduling_link(run.contract.client_name, email)
    return {"url": link.url, "event_type_uri": link.event_type_uri}
